atlas200mini_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

atlas200mini_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 40
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.25
  velocity_rolling_window_size: 2
  # Odom frame_id
  odom_frame_id: odom
  # Base frame_id
  base_frame_id: base_link
  # Odometry fused with IMU is published by robot_localization,
  # so no need to publish a TF based on encoders alone.
  enable_odom_tf: false
  # Atlas200mini hardware provides wheel velocities
  estimate_velocity_from_position: false
  # Wheel separation and radius multipliers
  wheel_separation: 0.7
  wheel_radius:     0.1275
  wheel_separation_multiplier: 1.2245 # 1.225 -value big, understeer; value small, oversteer
  wheel_radius_multiplier:     1.0 # 1.0
  # Velocity and Acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits:     true
      max_velocity:            10.0    # m/s
      has_acceleration_limits: true
      max_acceleration:        2.0    # m/s^2
  angular:
    z:
      has_velocity_limits:     true
      max_velocity:            2.0    # rad/s
      has_acceleration_limits: true
      max_acceleration:        1.0    # rad/s^2

#/gazebo_ros_control:
#  pid_gains:
#    front_left_wheel:
#      p: 1000.0
#      i: 0.01
#      d: 10.0
#    front_right_wheel:
#      p: 1000.0
#      i: 0.01
#      d: 10.0
#    rear_left_wheel:
#      p: 1000.0
#      i: 0.01
#      d: 10.0
#    rear_right_wheel:
#      p: 1000.0
#      i: 0.01
#      d: 10.0
